// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  image_text: defineAsyncComponent(() => import("./ImageText/index.vue")),
  link: defineAsyncComponent(() => import("./Link/index.vue")),
  title: defineAsyncComponent(() => import("./Title/index.vue")),
});
